export const FETCH_POST_DATA = 'FETCH_POST_DATA';
export const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS';
export const DELETE_POST = 'DELETE_POST';


export const FETCH_COMMENT_DATA = 'FETCH_COMMENT_DATA';
export const FETCH_COMMENT_DETAILS = 'FETCH_COMMENT_DETAILS';